### ISSUE TITLE
Are hostnames for topics ideal?

### ISSUE THREAD

**Issue by nateonawalk** [jkarlin/topics#18]
> We propose choosing topics of interest based only on website hostnames, rather than additional information like the full URL or contents of visited websites.

> This is a difficult trade-off: topics based on more specific browsing activity might be more useful in picking relevant ads, but also might unintentionally pick up data with heightened privacy expectations.

_Let's assume subdomains in this context are separate hostnames and we're using the terms interchangeably._

If publishers want to serve more relevant advertising, they're incentivized to send narrower topics. And if they are rewarded for sending narrower topics, then they're compelled to granularize their site into as many subdomains as possible without suffering traffic losses. 

Making subdomain-heavy site architecture monetarily advantageous for publishers raises some concerns. [@gui-poa's voiced this in another issue](https://github.com/jkarlin/topics/issues/1#issuecomment-1021830438). A few of mine:

1. Most mainstream CMSs sit on a single subdomain and allow for content creation/organization via directories only. "Multisite" options exist, but are typically an enterprise solution. In this way, large publishers who can engineer their own hostname-first CMS and afford devOps to manage multiple name systems may be afforded an unfair advantage over small/independent publishers

2. Subdomains have their taxonomical role in isolating use-cases (support.example.com) and localization (es.example.com, de.example.com)… but in my experience, using them for subcategorization (i.e. arts.example.com) complicates breadcrumbs, wrecks sitemaps, dirties or breaks analytics, and causes cross-origin problems

3. The SEO debate around subdomains vs subfolders is tired and isn't worth rehashing here (just search "subdomains SEO")

**Nightmare scenario:** Publisher sites link internally to pages hosted on granularly categorized subdomains to appease the Topics API, all of which are cross-canonicalized to a single subdirectory-first site that the publisher feels is better optimized for search engines. Users only ever see this subdirectory site as a landing page... it exists for bots.

What alternatives are there to the proposed "one topic per hostname" rule? Can one respect heightened privacy expectations (avoiding hyper-targeted, mappable Topic API sends) without nudging publishers toward subdomains?

**Comment by jkarlin** [comment]
I'm trying to figure out what the publisher's incentive is here for playing with domains. That their repeat visitors will get the more specific topics on future visits back to their site? Shouldn't those more specific topics already be available via 1p contextual advertising? E.g., I'm not sure that Topics API needs to be involved there.

**Comment by hu0p** [comment]
> I'm trying to figure out what the publisher's incentive is here for playing with domains

The incentive doesn't have to be a competitive one. The fact that misclassification is likely due to the limited information the classifier has to work with is enough. Without naming names, Ads platforms already have a difficult enough time correctly classifying and disapproving ads for sensitive topics, and they have access to more information than the hostname. It seems reasonable to think some publishers may be misclassified as irrelevant or, worse, sensitive topics based on hostname alone. 

With no other way to appeal or edit topics, it's not unreasonable to think that sites with mixed content or vague, generalized hostnames will play this game to avoid or resolve misclassification, and it seems really disheartening that some may even have to rebrand or change domains and deal with redirects to address these issues. The assumption that hostname classification can work well enough or will work well for everyone seems to be a big one here based on intuition and the details we currently have to go on alone.

**Comment by jkarlin** [comment]
> It seems reasonable to think some publishers may be misclassified as irrelevant or, worse, sensitive topics based on hostname alone.

Agree. This is going to happen from time to time. The next question is, which parties are affected? Misclassified topics mean that the user's topics are less relevant, and have less utility. This is bad, and we want to classify as best we can. But does a given publisher actually care if their own site is misclassified? I'd argue that they shouldn't. They won't make more money by changing their domain name. A publisher's value from the Topics API are the _other_ topics that a user has that aren't related to their site. The publisher already knows what their own site is about, and can gather contextual ads based on that.

Regardless, I do think we want to address misclassification. Either we constantly improve the model, or we allow for some kind of override list where we know the model is bad, or we allow sites/callers to somehow say for themselves what their topics are. The latter has privacy issues, and the middle requires some organization to maintain said list and ensure that it's accurate. 

I'd like to hold discussions on how pubs might update their classification to other existing issues and close this one out just to help me keep the number of unique issues down. So please refer to #2 .
