### ISSUE TITLE
Topic Aggregation and Ranking

### ISSUE THREAD

**Issue by stguav** [jkarlin/topics#46]
The [Topics API](https://github.com/jkarlin/topics) involves ranking the "top topics" for a user's browsing activity in one epoch. How would the API aggregate and rank a user's browsing activity to find the top 5 topics described in the explainer? 

Currently the explainer says https://github.com/jkarlin/topics#specific-details:  "at the end of an epoch, the browser calculates the list of eligible pages visited by the user in the previous week" and "the topics are accumulated".

More specifically, can you clarify:

1. If a user visits the same site multiple times, does that increase the ranking for the site's topics? If so,
    - Over what time period?    
    - What counts as a separate visit?
    - Is there some maximum saturation?

2. Will the classifier output be one-hot (unit-weight) or some fractional weight? Having weights may make the classification seem less arbitrary.
3. Will the classifier output take the taxonomy hierarchy into account? For example, if the site is classified as `/Computers & Electronics/Consumer Electronics/Cameras & Camcorders`, we can also include `/Computers & Electronics/Consumer Electronics` and `/Computers & Electronics`. This also should apply for per-caller eligibility.
4. How will the weights (unit or otherwise) be aggregated?
    - Could we consider some [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) based approach? The IDF could be implemented as a rescaling of the classifier output weight. Using a global IDF would allow the topics that are more likely to be useful to ad tech to rank higher.
    - Can we consider deduping/removing redundant topics? For example, if the more specific `/Computers & Electronics/Consumer Electronics/Cameras & Camcorders` is in the top 5, then it implies the more general `/Computers & Electronics`. Having a more diverse top 5 should improve the long-term utility.

One concern with the Topics API is that users' top topics will be dominated by broad, signal-poor topics. Choosing the taxonomy and weighting algorithm thoughtfully may help.

**Comment by jkarlin** [comment]
Great questions, but I want to consolidate this discussion to the existing issue #42
